/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ConsoleRouteRouteImport } from './routes/console/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleKeysRouteImport } from './routes/console/keys'
import { Route as ConsoleUsageRouteImport } from './routes/console/usage'
import { Route as ConsoleWalletRouteImport } from './routes/console/wallet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRouteRoute = ConsoleRouteRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleKeysRoute = ConsoleKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleUsageRoute = ConsoleUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => ConsoleRouteRoute,
} as any)
const ConsoleWalletRoute = ConsoleWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ConsoleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/keys': typeof ConsoleKeysRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console/keys': typeof ConsoleKeysRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/admin': typeof AdminIndexRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/console': typeof ConsoleRouteRouteWithChildren
  '/console/keys': typeof ConsoleKeysRoute
  '/console/usage': typeof ConsoleUsageRoute
  '/console/wallet': typeof ConsoleWalletRoute
  '/admin/': typeof AdminIndexRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/console'
    | '/console/keys'
    | '/console/usage'
    | '/console/wallet'
    | '/admin/'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console/keys'
    | '/console/usage'
    | '/console/wallet'
    | '/admin'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/console'
    | '/console/keys'
    | '/console/usage'
    | '/console/wallet'
    | '/admin/'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ConsoleRouteRoute: typeof ConsoleRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/keys': {
      id: '/console/keys'
      path: '/keys'
      fullPath: '/console/keys'
      preLoaderRoute: typeof ConsoleKeysRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/usage': {
      id: '/console/usage'
      path: '/usage'
      fullPath: '/console/usage'
      preLoaderRoute: typeof ConsoleUsageRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
    '/console/wallet': {
      id: '/console/wallet'
      path: '/wallet'
      fullPath: '/console/wallet'
      preLoaderRoute: typeof ConsoleWalletRouteImport
      parentRoute: typeof ConsoleRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ConsoleRouteRouteChildren {
  ConsoleKeysRoute: typeof ConsoleKeysRoute
  ConsoleUsageRoute: typeof ConsoleUsageRoute
  ConsoleWalletRoute: typeof ConsoleWalletRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteRouteChildren: ConsoleRouteRouteChildren = {
  ConsoleKeysRoute: ConsoleKeysRoute,
  ConsoleUsageRoute: ConsoleUsageRoute,
  ConsoleWalletRoute: ConsoleWalletRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteRouteWithChildren = ConsoleRouteRoute._addFileChildren(
  ConsoleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ConsoleRouteRoute: ConsoleRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
